---
abstract: 'Copy files from a release (for SCM inclusion, etc.)'
author:
  - 'Graham Knop <haarg@haarg.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CopyFilesFromRelease
requires:
  Dist::Zilla::Role::AfterRelease: 0
  File::Copy: 0
  Moose: 0
  Moose::Autobox: 0
  strict: 0
  warnings: 0
version: 0.001
